name: pwa
version: 0.1.12
author: Istvan Soos <istvan.soos@gmail.com>
description: Progressive Web App library

homepage: https://github.com/isoos/pwa

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  args: ^1.4.0
  dart_style: ">=0.2.16 <2.0.0"
  glob: ^1.1.3
  service_worker: '>=0.1.0 <0.3.0'
  yaml: ^2.1.12
