name: pwa
version: 0.0.5
author: Istvan Soos <istvan.soos@gmail.com>
description: Progressive Web App library

homepage: https://github.com/isoos/pwa

environment:
  sdk: ">=1.19.0 <2.0.0"

dependencies:
  args: ^0.13.7
  dart_style: ^0.2.16
  func: ^0.1.1
  glob: ^1.1.3
  service_worker: ^0.0.1
  yaml: ^2.1.12
