name: pwa_example
version: 0.0.1
author: Istvan Soos <istvan.soos@gmail.com>
description: PWA Example

environment:
  sdk: ">=1.19.0 <2.0.0"

dependencies:
  angular2: ^2.2.0
  pwa:
    path: '../../'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
